# Generated by Django 3.0 on 2019-12-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20191222_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='author',
            new_name='owner',
        ),
    ]
