# Generated by Django 3.0 on 2020-01-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20191227_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='author',
            new_name='owner',
        ),
    ]
