# Generated by Django 3.1.2 on 2020-11-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200104_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
