# Generated by Django 3.1.2 on 2020-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20201102_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
