# Generated by Django 3.1.2 on 2020-11-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20201102_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
