# Generated by Django 3.1.2 on 2020-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20201103_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.CharField(max_length=50, verbose_name='back'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.CharField(max_length=50, verbose_name='front'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
