# Generated by Django 3.0 on 2020-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200104_1136'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Flashcard')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.LearningSession')),
            ],
        ),
    ]
