# Generated by Django 3.0 on 2020-03-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200104_1136'),
        ('learn', '0003_auto_20200320_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Flashcard'),
        ),
    ]
