# Generated by Django 3.0 on 2020-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20200320_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='part_of_set',
            field=models.BooleanField(default=False),
        ),
    ]
