# Generated by Django 3.0 on 2020-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_learningsession_part_of_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
