# Generated by Django 3.0 on 2020-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20200521_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='learned',
            field=models.IntegerField(default=0),
        ),
    ]
